---
name: "xos-tosca"
gprc_endpoint: "xos-core:30001"
local_cert: ""
logging:
  version: 1
  handlers:
    console:
      class: logging.StreamHandler
  loggers:
    'multistructlog':
      handlers:
        - console
      level: ERROR
